In [1]:
import numpy as np
import pandas as pd

# Loading the data

## Loading towns

In [2]:
df = pd.read_csv('2020_maires_reelus.csv.gz', compression='gzip').dropna(how='all',axis='columns')
df.codeinsee = pd.to_numeric(df.codeinsee, errors='coerce', downcast='integer') 
df = df.rename(columns={"codeinsee": "code_insee"})
print(len(df))
df.head()

22725

/home/kelu/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (2,3,32,34,35) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Code du département,codmindpt,coddpt3car,libdpt,Code de la commune,libsubcom,typcom,popsubcom,modescrutin,...,code_insee,age_lors_elec,codnualisteinitiale,liblisextinitiale,NomElu2020,PrenomElu2020,% Voix/Ins,% Voix/Exp,type,matchPrenoms
0,0,1,1,1,AIN,5.0,Ambérieux-en-Dombes,Commune,1600.0,Liste,...,1005.0,52,NaN,NaN,PERNET,Pierre,26.99,100.00,small,100
1,1,1,1,1,AIN,7.0,Ambronay,Commune,2365.0,Liste,...,1007.0,59,NaN,NaN,BARILLOT,Marie-Christine,27.96,50.23,small,100
2,2,1,1,1,AIN,10.0,Anglefort,Commune,1031.0,Liste,...,1010.0,65,NaN,NaN,THIBOUD,Bernard,25.97,100.00,small,100
3,3,1,1,1,AIN,21.0,Ars-sur-Formans,Commune,1374.0,Liste,...,1021.0,61,NaN,NaN,PACCAUD,Richard,34.03,100.00,small,100
4,4,1,1,1,AIN,22.0,Artemare,Commune,1140.0,Liste,...,1022.0,57,NaN,NaN,DESCHAMPS,Roland,42.12,62.15,small,100

In [3]:
df[df.matchPrenoms < 90][['PrenomElu2020','PrenomElu2014','matchPrenoms']]

      PrenomElu2020 PrenomElu2014  matchPrenoms
29         Michelle       Michèle            71
34          Mickaël     Catherine            14
59            Henri     Véronique            40
98             Jean      Sandrine            50
101          Pierre         Annie            40
...             ...           ...           ...
22658        Pierre          Anna             0
22661        Julien       Laurent            50
22691         André         Andre            80
22703   Jean-Michel         Louis            20
22722     Véronique     VERONIQUE            89

[3044 rows x 3 columns]

In [17]:
df = df[df.matchPrenoms >= 80]
len(df)
listInseeReelus = list(df.code_insee.unique())
#print(listInseeReelus)
df.to_csv('2020_reelected_mayors.csv.gz', compression='gzip')

## Loading towns details

In [5]:
#pdCommunes = pd.read_csv("data/communes/communes_gps.csv", sep=';', quotechar='"')
#pdCommunes.code_insee = pd.to_numeric(pdCommunes.code_insee, errors='coerce', downcast='integer')  
#pdCommunes.to_pickle("./data/pdCommunes.pkl")
pdCommunes = pd.read_pickle("./data/pdCommunes.pkl")
print(len(pdCommunes))
pdCommunes.head()

36840

,EU_circo,code_région,nom_région,chef-lieu_région,numéro_département,nom_département,préfecture,numéro_circonscription,nom_commune,codes_postaux,code_insee,latitude,longitude,éloignement
0,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Attignat,01340,1024,46.283333,5.166667,1.21
1,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Beaupont,01270,1029,46.4,5.266667,1.91
2,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Bény,01370,1038,46.333333,5.283333,1.51
3,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Béreyziat,01340,1040,46.366667,5.05,1.71
4,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Bohas-Meyriat-Rignat,01250,1245,46.133333,5.4,1.01

## Loading Insee stats

In [10]:
#pdInsee = pd.read_excel("data/communes/MDB-INSEE-V2.xls")
#pdInsee.CODGEO = pd.to_numeric(pdInsee.CODGEO, errors='coerce', downcast='integer')  
#pdInsee = pdInsee.rename(columns={"CODGEO": "code_insee"})
#pdInsee["Reelected"] = pdInsee.code_insee.apply(lambda x: x in(listInseeReelus))
#pdInsee.to_pickle("./data/pdInsee.pkl")
pdInsee = pd.read_pickle("./data/pdInsee.pkl")
print(len(pdInsee))
pdInsee.head()

36677

,code_insee,Nb Pharmacies et parfumerie,Dynamique Entrepreneuriale,Dynamique Entrepreneuriale Service et Commerce,Synergie Médicale COMMUNE,Orientation Economique,Indice Fiscal Partiel,Score Fiscal,Indice Evasion Client,Score Evasion Client,...,Score VA Région,Score PIB,Environnement Démographique,Fidélité,SYN MEDICAL,Seg Cap Fiscale,Seg Dyn Entre,DYN SetC,CP,Reelected
0,1001.0,0.0,57.0,23.0,114,Bassin Industriel,101.93878,59.04139,0.00000,0.00000,...,32.42578,33.83811,Bassin Industriel en croissance démographique,Pop Sédentaire,Synergie Médicale,Fiscalité moyenne,Faible dynamique,Faible Dynamique Serv et Com,01,True
1,1002.0,0.0,45.0,4.0,143,Bassin Résidentiel,101.93878,59.04139,0.00000,0.00000,...,32.42578,33.83811,Bassin Résidentiel en croissance démographique,Pop Sédentaire,Forte Synergie Médicale,Fiscalité moyenne,Faible dynamique,Faible Dynamique Serv et Com,01,True
2,1004.0,0.0,634.0,828.0,366,Bassin Résidentiel,101.93878,59.04139,248.45549,0.10621,...,32.42578,33.83811,Bassin Résidentiel en croissance démographique,Pop Mobile,Forte Synergie Médicale,Fiscalité moyenne,Dynamique Economique,Bonne Dynamique Entreprise Serv et Com,01,False
3,1005.0,0.0,113.0,62.0,132,Bassin Urbain,101.93878,59.04139,248.45549,0.10621,...,32.42578,33.83811,Bassin Urbain en croissance démographique,Pop Mobile,Forte Synergie Médicale,Fiscalité moyenne,Moyenne dynamique,Faible Dynamique Serv et Com,01,True
4,1006.0,0.0,42.0,1.0,121,Bassin Résidentiel,101.93878,59.04139,0.00000,0.00000,...,32.42578,33.83811,Bassin Résidentiel en croissance démographique,Pop Sédentaire,Forte Synergie Médicale,Fiscalité moyenne,Faible dynamique,Faible Dynamique Serv et Com,01,True

In [16]:
pdTowns = pdInsee.merge(pdCommunes,on="code_insee",how="left")
pdTowns.to_pickle("./data/pdTowns.pkl")
pdTowns.to_csv('2020_towns.csv.gz', compression='gzip')